import type { ChatMessage, RecruiterScore } from "@/types/chat";

function formatScore(score: RecruiterScore): string {
  const lines = [
    `**Overall:** ${score.overall}/100`,
    "",
    "**Categories**",
    `- Communication: ${score.categories.communication}%`,
    `- Confidence: ${score.categories.confidence}%`,
    `- Professionalism: ${score.categories.professionalism}%`,
    `- Technical clarity: ${score.categories.technicalClarity}%`,
    `- GCC readiness: ${score.categories.gccReadiness}%`,
    "",
    `**Summary:** ${score.summary}`,
    "",
    "**Strengths**",
    ...score.strengths.map((s) => `- ${s}`),
    "",
    "**Needs improvement**",
    ...score.needsImprovement.map((s) => `- ${s}`),
  ];
  return lines.join("\n");
}

export function buildPrepPacketMarkdown(opts: {
  generatedAt: Date;
  jobDescription: string;
  messages: ChatMessage[];
  score: RecruiterScore | null;
}): string {
  const { generatedAt, jobDescription, messages, score } = opts;
  const jd = jobDescription.trim();
  const transcript = messages
    .filter((m) => m.role === "user" || m.role === "assistant")
    .map((m) => `### ${m.role === "user" ? "Candidate" : "Interviewer"}\n\n${m.content.trim()}`)
    .join("\n\n---\n\n");

  const parts = [
    "# FalconHire — interview prep packet",
    "",
    `_Generated ${generatedAt.toISOString()}_`,
    "",
    "> Coaching artifact only—not employment, legal, or immigration advice.",
    "",
    "## Target job description",
    "",
    jd ? jd : "_No job description was attached for this session._",
    "",
    "## Mock interview transcript",
    "",
    transcript.trim() ? transcript : "_No messages yet._",
    "",
  ];

  if (score) {
    parts.push("## Recruiter-style score", "", formatScore(score), "");
  } else {
    parts.push(
      "## Recruiter-style score",
      "",
      "_No score generated yet—use “Generate score” in the app, then download again._",
      "",
    );
  }

  parts.push("---", "", "_Generated by FalconHire AI — mock interview prep packet._");
  return parts.join("\n");
}
